config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :delete]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :assignments, :module => 'users', only: [:index]
        resources :answers, :module => 'users', only: [:index]
      end
      resources :homeworks, only: [:index, :create, :show, :update, :destroy] do
        resources :assignments, :module => 'homeworks', only: [:index, :create, :destroy]
        resources :answers, :module => 'homeworks', only: [:index, :show, :create]
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<% if current_user %>
  <%= javascript_tag do %>
    var current_user = <%=raw current_user.to_json %>;
  <% end %>
<% end %>
</head>
<body class="<%= params[:controller].parameterize %> <%= params[:action].parameterize %>" role="document">
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Homework", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li>
            <%= link_to "Logout", logout_url %>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
<div class="container">
<%= yield %>
</div>
</body>
</html>